//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsReniec
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", ConfigurationName="wsReniec.GestionPersonaWS")]
    internal interface GestionPersonaWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsReniec.obtenerDatosPorRUCResponse> obtenerDatosPorRUCAsync(wsReniec.obtenerDatosPorRUCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsReniec.obtenerDatosCadenaPorRUCResponse> obtenerDatosCadenaPorRUCAsync(wsReniec.obtenerDatosCadenaPorRUCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsReniec.verificarRazonSocialRUCResponse> verificarRazonSocialRUCAsync(wsReniec.verificarRazonSocialRUCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsReniec.guardarPersonaPorIDResponse> guardarPersonaPorIDAsync(wsReniec.guardarPersonaPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsReniec.guardarPersonaPorRUCResponse> guardarPersonaPorRUCAsync(wsReniec.guardarPersonaPorRUCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsReniec.obtenerDatosReniecResponse> obtenerDatosReniecAsync(wsReniec.obtenerDatosReniecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsReniec.logCallExternalWebServicesSMSResponse> logCallExternalWebServicesSMSAsync(wsReniec.logCallExternalWebServicesSMSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/")]
    public partial class persona
    {
        
        private string idField;
        
        private string nombreRazonSocialField;
        
        private string personaTipoField;
        
        private string documentoTipoField;
        
        private string documentoNumeroField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private string rucField;
        
        private string nombresField;
        
        private string direccionField;
        
        private string departamentoField;
        
        private string provinciaField;
        
        private string distritoField;
        
        private string telefonoField;
        
        private string centroPobladoField;
        
        private string telefonoMovilField;
        
        private string correoElectronicoField;
        
        private string referenciaDireccionField;
        
        private string estadoNaturalField;
        
        private string estadoJuridicoField;
        
        private string fechaAltaField;
        
        private string fechaBajaField;
        
        private string paisField;
        
        private string fechaNacimientoField;
        
        private string nombreComercialField;
        
        private string ndepartamentoField;
        
        private string nprovinciaField;
        
        private string ndistritoField;
        
        private string estadoCivilField;
        
        private string coResultadoField;
        
        private string deResultadoField;
        
        private representanteLegal[] representantesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string nombreRazonSocial
        {
            get
            {
                return this.nombreRazonSocialField;
            }
            set
            {
                this.nombreRazonSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string personaTipo
        {
            get
            {
                return this.personaTipoField;
            }
            set
            {
                this.personaTipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string documentoTipo
        {
            get
            {
                return this.documentoTipoField;
            }
            set
            {
                this.documentoTipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string documentoNumero
        {
            get
            {
                return this.documentoNumeroField;
            }
            set
            {
                this.documentoNumeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string apellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ruc
        {
            get
            {
                return this.rucField;
            }
            set
            {
                this.rucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string nombres
        {
            get
            {
                return this.nombresField;
            }
            set
            {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string departamento
        {
            get
            {
                return this.departamentoField;
            }
            set
            {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string provincia
        {
            get
            {
                return this.provinciaField;
            }
            set
            {
                this.provinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string distrito
        {
            get
            {
                return this.distritoField;
            }
            set
            {
                this.distritoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string centroPoblado
        {
            get
            {
                return this.centroPobladoField;
            }
            set
            {
                this.centroPobladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string telefonoMovil
        {
            get
            {
                return this.telefonoMovilField;
            }
            set
            {
                this.telefonoMovilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string correoElectronico
        {
            get
            {
                return this.correoElectronicoField;
            }
            set
            {
                this.correoElectronicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string referenciaDireccion
        {
            get
            {
                return this.referenciaDireccionField;
            }
            set
            {
                this.referenciaDireccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string estadoNatural
        {
            get
            {
                return this.estadoNaturalField;
            }
            set
            {
                this.estadoNaturalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string estadoJuridico
        {
            get
            {
                return this.estadoJuridicoField;
            }
            set
            {
                this.estadoJuridicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string fechaAlta
        {
            get
            {
                return this.fechaAltaField;
            }
            set
            {
                this.fechaAltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string fechaBaja
        {
            get
            {
                return this.fechaBajaField;
            }
            set
            {
                this.fechaBajaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string pais
        {
            get
            {
                return this.paisField;
            }
            set
            {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string fechaNacimiento
        {
            get
            {
                return this.fechaNacimientoField;
            }
            set
            {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string nombreComercial
        {
            get
            {
                return this.nombreComercialField;
            }
            set
            {
                this.nombreComercialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string ndepartamento
        {
            get
            {
                return this.ndepartamentoField;
            }
            set
            {
                this.ndepartamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string nprovincia
        {
            get
            {
                return this.nprovinciaField;
            }
            set
            {
                this.nprovinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string ndistrito
        {
            get
            {
                return this.ndistritoField;
            }
            set
            {
                this.ndistritoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=28)]
        public string estadoCivil
        {
            get
            {
                return this.estadoCivilField;
            }
            set
            {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string coResultado
        {
            get
            {
                return this.coResultadoField;
            }
            set
            {
                this.coResultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string deResultado
        {
            get
            {
                return this.deResultadoField;
            }
            set
            {
                this.deResultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("representantes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=31)]
        public representanteLegal[] representantes
        {
            get
            {
                return this.representantesField;
            }
            set
            {
                this.representantesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/")]
    public partial class representanteLegal
    {
        
        private string cargoField;
        
        private string documentoNumeroField;
        
        private string documentoTipoField;
        
        private string fechaCargoField;
        
        private string idField;
        
        private string nombreCompletoField;
        
        private int ordenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cargo
        {
            get
            {
                return this.cargoField;
            }
            set
            {
                this.cargoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string documentoNumero
        {
            get
            {
                return this.documentoNumeroField;
            }
            set
            {
                this.documentoNumeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string documentoTipo
        {
            get
            {
                return this.documentoTipoField;
            }
            set
            {
                this.documentoTipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fechaCargo
        {
            get
            {
                return this.fechaCargoField;
            }
            set
            {
                this.fechaCargoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombreCompleto
        {
            get
            {
                return this.nombreCompletoField;
            }
            set
            {
                this.nombreCompletoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int orden
        {
            get
            {
                return this.ordenField;
            }
            set
            {
                this.ordenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosPorRUC", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class obtenerDatosPorRUCRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public obtenerDatosPorRUCRequest()
        {
        }
        
        public obtenerDatosPorRUCRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosPorRUCResponse", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class obtenerDatosPorRUCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsReniec.persona @return;
        
        public obtenerDatosPorRUCResponse()
        {
        }
        
        public obtenerDatosPorRUCResponse(wsReniec.persona @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosCadenaPorRUC", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class obtenerDatosCadenaPorRUCRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public obtenerDatosCadenaPorRUCRequest()
        {
        }
        
        public obtenerDatosCadenaPorRUCRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosCadenaPorRUCResponse", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class obtenerDatosCadenaPorRUCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public obtenerDatosCadenaPorRUCResponse()
        {
        }
        
        public obtenerDatosCadenaPorRUCResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarRazonSocialRUC", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class verificarRazonSocialRUCRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public verificarRazonSocialRUCRequest()
        {
        }
        
        public verificarRazonSocialRUCRequest(string arg0, string arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarRazonSocialRUCResponse", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class verificarRazonSocialRUCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public verificarRazonSocialRUCResponse()
        {
        }
        
        public verificarRazonSocialRUCResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarPersonaPorID", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class guardarPersonaPorIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public guardarPersonaPorIDRequest()
        {
        }
        
        public guardarPersonaPorIDRequest(string arg0, string arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarPersonaPorIDResponse", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class guardarPersonaPorIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public guardarPersonaPorIDResponse()
        {
        }
        
        public guardarPersonaPorIDResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarPersonaPorRUC", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class guardarPersonaPorRUCRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public guardarPersonaPorRUCRequest()
        {
        }
        
        public guardarPersonaPorRUCRequest(string arg0, string arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarPersonaPorRUCResponse", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class guardarPersonaPorRUCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public guardarPersonaPorRUCResponse()
        {
        }
        
        public guardarPersonaPorRUCResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosReniec", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class obtenerDatosReniecRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public obtenerDatosReniecRequest()
        {
        }
        
        public obtenerDatosReniecRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosReniecResponse", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class obtenerDatosReniecResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsReniec.persona @return;
        
        public obtenerDatosReniecResponse()
        {
        }
        
        public obtenerDatosReniecResponse(wsReniec.persona @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logCallExternalWebServicesSMS", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class logCallExternalWebServicesSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.gestionpersona.senasa.gob.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public logCallExternalWebServicesSMSRequest()
        {
        }
        
        public logCallExternalWebServicesSMSRequest(string arg0, string arg1, string arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logCallExternalWebServicesSMSResponse", WrapperNamespace="http://ws.gestionpersona.senasa.gob.pe/", IsWrapped=true)]
    internal partial class logCallExternalWebServicesSMSResponse
    {
        
        public logCallExternalWebServicesSMSResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    internal interface GestionPersonaWSChannel : wsReniec.GestionPersonaWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    internal partial class GestionPersonaWSClient : System.ServiceModel.ClientBase<wsReniec.GestionPersonaWS>, wsReniec.GestionPersonaWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GestionPersonaWSClient() : 
                base(GestionPersonaWSClient.GetDefaultBinding(), GestionPersonaWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.GestionPersonaWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GestionPersonaWSClient(EndpointConfiguration endpointConfiguration) : 
                base(GestionPersonaWSClient.GetBindingForEndpoint(endpointConfiguration), GestionPersonaWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GestionPersonaWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GestionPersonaWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GestionPersonaWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GestionPersonaWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GestionPersonaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsReniec.obtenerDatosPorRUCResponse> wsReniec.GestionPersonaWS.obtenerDatosPorRUCAsync(wsReniec.obtenerDatosPorRUCRequest request)
        {
            return base.Channel.obtenerDatosPorRUCAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsReniec.obtenerDatosPorRUCResponse> obtenerDatosPorRUCAsync(string arg0)
        {
            wsReniec.obtenerDatosPorRUCRequest inValue = new wsReniec.obtenerDatosPorRUCRequest();
            inValue.arg0 = arg0;
            return ((wsReniec.GestionPersonaWS)(this)).obtenerDatosPorRUCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsReniec.obtenerDatosCadenaPorRUCResponse> wsReniec.GestionPersonaWS.obtenerDatosCadenaPorRUCAsync(wsReniec.obtenerDatosCadenaPorRUCRequest request)
        {
            return base.Channel.obtenerDatosCadenaPorRUCAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsReniec.obtenerDatosCadenaPorRUCResponse> obtenerDatosCadenaPorRUCAsync(string arg0)
        {
            wsReniec.obtenerDatosCadenaPorRUCRequest inValue = new wsReniec.obtenerDatosCadenaPorRUCRequest();
            inValue.arg0 = arg0;
            return ((wsReniec.GestionPersonaWS)(this)).obtenerDatosCadenaPorRUCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsReniec.verificarRazonSocialRUCResponse> wsReniec.GestionPersonaWS.verificarRazonSocialRUCAsync(wsReniec.verificarRazonSocialRUCRequest request)
        {
            return base.Channel.verificarRazonSocialRUCAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsReniec.verificarRazonSocialRUCResponse> verificarRazonSocialRUCAsync(string arg0, string arg1)
        {
            wsReniec.verificarRazonSocialRUCRequest inValue = new wsReniec.verificarRazonSocialRUCRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((wsReniec.GestionPersonaWS)(this)).verificarRazonSocialRUCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsReniec.guardarPersonaPorIDResponse> wsReniec.GestionPersonaWS.guardarPersonaPorIDAsync(wsReniec.guardarPersonaPorIDRequest request)
        {
            return base.Channel.guardarPersonaPorIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsReniec.guardarPersonaPorIDResponse> guardarPersonaPorIDAsync(string arg0, string arg1)
        {
            wsReniec.guardarPersonaPorIDRequest inValue = new wsReniec.guardarPersonaPorIDRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((wsReniec.GestionPersonaWS)(this)).guardarPersonaPorIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsReniec.guardarPersonaPorRUCResponse> wsReniec.GestionPersonaWS.guardarPersonaPorRUCAsync(wsReniec.guardarPersonaPorRUCRequest request)
        {
            return base.Channel.guardarPersonaPorRUCAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsReniec.guardarPersonaPorRUCResponse> guardarPersonaPorRUCAsync(string arg0, string arg1)
        {
            wsReniec.guardarPersonaPorRUCRequest inValue = new wsReniec.guardarPersonaPorRUCRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((wsReniec.GestionPersonaWS)(this)).guardarPersonaPorRUCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsReniec.obtenerDatosReniecResponse> wsReniec.GestionPersonaWS.obtenerDatosReniecAsync(wsReniec.obtenerDatosReniecRequest request)
        {
            return base.Channel.obtenerDatosReniecAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsReniec.obtenerDatosReniecResponse> obtenerDatosReniecAsync(string arg0)
        {
            wsReniec.obtenerDatosReniecRequest inValue = new wsReniec.obtenerDatosReniecRequest();
            inValue.arg0 = arg0;
            return ((wsReniec.GestionPersonaWS)(this)).obtenerDatosReniecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsReniec.logCallExternalWebServicesSMSResponse> wsReniec.GestionPersonaWS.logCallExternalWebServicesSMSAsync(wsReniec.logCallExternalWebServicesSMSRequest request)
        {
            return base.Channel.logCallExternalWebServicesSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsReniec.logCallExternalWebServicesSMSResponse> logCallExternalWebServicesSMSAsync(string arg0, string arg1, string arg2)
        {
            wsReniec.logCallExternalWebServicesSMSRequest inValue = new wsReniec.logCallExternalWebServicesSMSRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((wsReniec.GestionPersonaWS)(this)).logCallExternalWebServicesSMSAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GestionPersonaWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GestionPersonaWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://bpm.senasa.gob.pe:7003/GestionPersonaWS/GestionPersonaWSPort");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GestionPersonaWSClient.GetBindingForEndpoint(EndpointConfiguration.GestionPersonaWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GestionPersonaWSClient.GetEndpointAddress(EndpointConfiguration.GestionPersonaWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            GestionPersonaWSPort,
        }
    }
}
